ruff linter check added to CI

diff --git a/.github/workflows/ci_linting.yml b/.github/workflows/ci_linting.yml
--- a/.github/workflows/ci_linting.yml
+++ b/.github/workflows/ci_linting.yml
@@ -74,6 +74,7 @@ jobs:
         run: |
           ./codebuild/bin/run_kwstyle.sh
           ./codebuild/bin/cpp_style_comment_linter.sh
+
   ruff:
     runs-on: ubuntu-latest
     steps:
@@ -94,6 +95,27 @@ jobs:
         run: |
             echo "Run 'ruff format .' to fix formatting issues"
             exit 1
+
+  ruff-lint:
+    runs-on: ubuntu-latest
+    steps:
+      - name: checkout
+        uses: actions/checkout@v4
+
+      - name: Set up uv
+        uses: astral-sh/setup-uv@v5
+
+      - name: Run Ruff lint check
+        working-directory: tests/integrationv2
+        id: ruff_lint
+        run: uv run ruff check .
+        continue-on-error: true
+
+      - name: Check exit code
+        if: steps.ruff_lint.outcome == 'failure'
+        run: |
+          echo "Linting issues detected. Run 'ruff check .' locally to see errors and fix them."
+          exit 1
   clang-format:
     runs-on: ubuntu-latest
     steps:
