feat: Expose `as_ptr()` for external build

diff --git a/.github/workflows/ci_rust.yml b/.github/workflows/ci_rust.yml
--- a/.github/workflows/ci_rust.yml
+++ b/.github/workflows/ci_rust.yml
@@ -75,6 +75,35 @@ jobs:
         # invoked on the `cargo test --all-features` pattern.
         run: RUST_LOG=TRACE cargo test --no-default-features --features pq
 
+  external-build-test:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Install Rust toolchain
+        id: toolchain
+        run: |
+          rustup toolchain install stable
+          rustup override set stable
+
+      - uses: camshaft/rust-cache@v1
+
+      - name: Checkout aws-lc
+        uses: actions/checkout@v4
+        with:
+          repository: aws/aws-lc
+          path: aws-lc
+
+      - name: Build aws-lc
+        working-directory: aws-lc
+        run: |
+          cmake -Bbuild \
+            -DBUILD_SHARED_LIBS=off \
+            -DBUILD_LIBSSL=off \
+            -DCMAKE_INSTALL_PREFIX=./install
+          cmake --build build -j $(nproc)
+          cmake --install build
+
       - name: Test external build
         # if this test is failing, make sure that api headers are appropriately
         # included. For a symbol to be visible in a shared lib, the
@@ -82,9 +111,14 @@ jobs:
         # in the same unit of compilation as the definition. Generally this just
         # means that if the linker can't resolve foo_method in tls/foo.c, you
         # forgot to include api/unstable/foo.h in tls/foo.c
-        if: ${{ matrix.os == 'ubuntu-latest' }}
         run: |
-          cmake . -Bbuild -DBUILD_SHARED_LIBS=on -DBUILD_TESTING=off
+          set -e
+
+          cmake . -Bbuild \
+            -DBUILD_SHARED_LIBS=on \
+            -DBUILD_TESTING=off \
+            -DCMAKE_PREFIX_PATH=./aws-lc/install \
+            -DS2N_INTERN_LIBCRYPTO=on
           cmake --build build -- -j $(nproc)
 
           export S2N_TLS_LIB_DIR=`pwd`/build/lib
@@ -96,6 +130,17 @@ jobs:
           # Relative paths
           cd ../../..
           ldd ${{env.STANDARD_PATH}}/target/debug/integration | grep libs2n.so
+
+          # Run tests with the external build
+          cargo test --manifest-path ${{env.ROOT_PATH}}/Cargo.toml
+          cargo test --manifest-path ${{env.STANDARD_PATH}}/Cargo.toml
+
+          echo ""
+          echo "Test that the external build will enable the proper cfg flag in s2n-tls. The"
+          echo "test_unstable_as_ptr test is gated behind this flag, so ensure this test is run."
+          output=$(cargo test --manifest-path ${{env.ROOT_PATH}}/s2n-tls/Cargo.toml test_unstable_as_ptr)
+          echo "${output}"
+          echo "${output}" | grep -q "test result: ok. 1 passed; 0 failed; 0 ignored;"
 
   # our benchmark testing includes interop tests between s2n-tls, rustls, and
   # openssl
